name: zebra_bluetooth_example
description: Demonstrates how to use the zebra_bluetooth plugin.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=3.6.1 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

  zebra_bluetooth:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
