name: zebra_bluetooth
description: Zebra Bluetooth printer plugin
version: 0.1.0
homepage:

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  dart_code_metrics: ^4.9.1
  flutter_lints: ^1.0.4
  freezed: ^1.1.1
  json_serializable: ^6.1.4

flutter:
  plugin:
    platforms:
      android:
        package: com.awcoding.zebra_bluetooth
        pluginClass: ZebraBluetoothPlugin
