name: zebra_bluetooth
description: Zebra Bluetooth printer plugin
version: 0.2.0
homepage:

environment:
  sdk: ">=3.6.1 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  flutter_lints: ^5.0.0
  freezed: ^3.0.6
  json_serializable: ^6.9.4

flutter:
  plugin:
    platforms:
      android:
        package: com.awcoding.zebra_bluetooth
        pluginClass: ZebraBluetoothPlugin
